<?php
/**
 * template for displaying informations for Pfay_Test module (in backend)
 */
?>
<form action="<?php //echo Mage::getUrl('test/index/savecontact') ?>" method="post">
  <fieldset>
    <ul>
     <li>
       <label for="nom">Nom</label>
       <input type="text" id="nom" name="nom" />
     </li>
     <li>
         <label for="prenom ">Prenom</label>
         <input type="text" id="prenom" name="prenom" />
     </li>
     <li>
        <label for="telephone">Telephone</label>
        <input type="text" id="telephone" name="telephone" />
    </li>
     <li>
        <input type="submit" value="Save" />
    </li>
  </ul>
 </fieldset>
 <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"  />
</form>

<?php
	//echo $this->createNewContact();
	echo '<br>';	
	echo $this->showAllContacts();
	echo '<br>';
	echo $this->editFirstContact();
?>