<?php
/**
 * template for displaying informations for Pfay_Test module
 */
?>
<form action="<?php echo Mage::getUrl('*/index/savecontact') ?>" method="post">
  <fieldset>
    <ul>
     <li>
       <label for="nom">Nom</label>
       <input type="text" id="nom" name="nom" />
     </li>
     <li>
         <label for="prenom ">Prenom</label>
         <input type="text" id="prenom" name="prenom" />
     </li>
     <li>
        <label for="telephone">Telephone</label>
        <input type="text" id="telephone" name="telephone" />
    </li>
     <li>
        <input type="submit" value="Save" />
    </li>
  </ul>
 </fieldset>
</form>

<?php
	//echo $this->createNewContact();
	echo '<br>';	
	echo $this->showAllContacts();
	echo '<br>';
	echo $this->editFirstContact();
	echo "<h2>Utilisation du Helper test/data</h2>";
	echo $this->methodblock();
?>